name: Generate Directory Structure

on:
  push:
    branches:
      - main  # Trigger on commits to main branch

jobs:
  generate-structure:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to commit changes

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: true  # Required for push access

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run directory scanner
      run: python directory_to_json.py  # Ensure your script outputs index.json

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add index.json
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update index.json from directory structure"
          git push
        fi
